// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/utils"
)

type Error struct {
	code    string `const:"bad_request" json:"code"`
	message string `const:"One of the provided values in the request query, body or headers is invalid" json:"message"`
}

func (e Error) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *Error) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Error) GetCode() string {
	return "bad_request"
}

func (o *Error) GetMessage() string {
	return "One of the provided values in the request query, body or headers is invalid"
}

type VercelBadRequestError struct {
	Error_ Error `json:"error"`
}

var _ error = &VercelBadRequestError{}

func (e *VercelBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
