// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetV1AccessGroupsIDOrName(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "readAccessGroup[0]":
			dir.HandlerFunc("readAccessGroup", testReadAccessGroupReadAccessGroup0)(w, req)
		case "readAccessGroup-id[0]":
			dir.HandlerFunc("readAccessGroup", testReadAccessGroupReadAccessGroupId0)(w, req)
		case "readAccessGroup-name[0]":
			dir.HandlerFunc("readAccessGroup", testReadAccessGroupReadAccessGroupName0)(w, req)
		default:
			http.Error(w, "Unknown test: "+test, http.StatusBadRequest)
		}
	}
}

func testReadAccessGroupReadAccessGroup0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, true, "Bearer"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &operations.ReadAccessGroupResponseBody{
		IsDsyncManaged: false,
		Name:           "my-access-group",
		CreatedAt:      "1588720733602",
		TeamID:         "team_123a6c5209bc3778245d011443644c8d27dc2c50",
		UpdatedAt:      "1588720733602",
		AccessGroupID:  "ag_123a6c5209bc3778245d011443644c8d27dc2c50",
		MembersCount:   5,
		ProjectsCount:  2,
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testReadAccessGroupReadAccessGroupId0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, true, "Bearer"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &operations.ReadAccessGroupResponseBody{
		IsDsyncManaged: false,
		Name:           "my-access-group",
		CreatedAt:      "1588720733602",
		TeamID:         "team_123a6c5209bc3778245d011443644c8d27dc2c50",
		UpdatedAt:      "1588720733602",
		AccessGroupID:  "ag_123a6c5209bc3778245d011443644c8d27dc2c50",
		MembersCount:   5,
		ProjectsCount:  2,
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}

func testReadAccessGroupReadAccessGroupName0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, true, "Bearer"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	respBody := &operations.ReadAccessGroupResponseBody{
		IsDsyncManaged: false,
		Name:           "my-access-group",
		CreatedAt:      "1588720733602",
		TeamID:         "team_123a6c5209bc3778245d011443644c8d27dc2c50",
		UpdatedAt:      "1588720733602",
		AccessGroupID:  "ag_123a6c5209bc3778245d011443644c8d27dc2c50",
		MembersCount:   5,
		ProjectsCount:  2,
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
