// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

// QueryParamType - In which status of the domain the price needs to be checked.
type QueryParamType string

const (
	QueryParamTypeNew        QueryParamType = "new"
	QueryParamTypeRenewal    QueryParamType = "renewal"
	QueryParamTypeTransfer   QueryParamType = "transfer"
	QueryParamTypeRedemption QueryParamType = "redemption"
)

func (e QueryParamType) ToPointer() *QueryParamType {
	return &e
}
func (e *QueryParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "new":
		fallthrough
	case "renewal":
		fallthrough
	case "transfer":
		fallthrough
	case "redemption":
		*e = QueryParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamType: %v", v)
	}
}

type CheckDomainPriceRequest struct {
	// The name of the domain for which the price needs to be checked.
	Name string `queryParam:"style=form,explode=true,name=name"`
	// In which status of the domain the price needs to be checked.
	Type *QueryParamType `queryParam:"style=form,explode=true,name=type"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *CheckDomainPriceRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CheckDomainPriceRequest) GetType() *QueryParamType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *CheckDomainPriceRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *CheckDomainPriceRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

// CheckDomainPriceResponseBody - Successful response which returns the price of the domain and the period.
type CheckDomainPriceResponseBody struct {
	// The domain price in USD.
	Price float64 `json:"price"`
	// The number of years the domain could be held before paying again.
	Period float64 `json:"period"`
}

func (o *CheckDomainPriceResponseBody) GetPrice() float64 {
	if o == nil {
		return 0.0
	}
	return o.Price
}

func (o *CheckDomainPriceResponseBody) GetPeriod() float64 {
	if o == nil {
		return 0.0
	}
	return o.Period
}

type CheckDomainPriceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response which returns the price of the domain and the period.
	Object *CheckDomainPriceResponseBody
}

func (o *CheckDomainPriceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CheckDomainPriceResponse) GetObject() *CheckDomainPriceResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
