// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteEdgeConfigTokensRequestBody struct {
	Tokens []string `json:"tokens"`
}

func (o *DeleteEdgeConfigTokensRequestBody) GetTokens() []string {
	if o == nil {
		return []string{}
	}
	return o.Tokens
}

type DeleteEdgeConfigTokensRequest struct {
	EdgeConfigID string `pathParam:"style=simple,explode=false,name=edgeConfigId"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug        *string                           `queryParam:"style=form,explode=true,name=slug"`
	RequestBody DeleteEdgeConfigTokensRequestBody `request:"mediaType=application/json"`
}

func (o *DeleteEdgeConfigTokensRequest) GetEdgeConfigID() string {
	if o == nil {
		return ""
	}
	return o.EdgeConfigID
}

func (o *DeleteEdgeConfigTokensRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *DeleteEdgeConfigTokensRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *DeleteEdgeConfigTokensRequest) GetRequestBody() DeleteEdgeConfigTokensRequestBody {
	if o == nil {
		return DeleteEdgeConfigTokensRequestBody{}
	}
	return o.RequestBody
}

type DeleteEdgeConfigTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteEdgeConfigTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
