// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAuthTokenRequest struct {
	// The identifier of the token to retrieve. The special value \"current\" may be supplied, which returns the metadata for the token that the current HTTP request is authenticated with.
	TokenID string `pathParam:"style=simple,explode=false,name=tokenId"`
}

func (o *GetAuthTokenRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

// GetAuthTokenResponseBody - Successful response.
type GetAuthTokenResponseBody struct {
	// Authentication token metadata.
	Token components.AuthToken `json:"token"`
}

func (o *GetAuthTokenResponseBody) GetToken() components.AuthToken {
	if o == nil {
		return components.AuthToken{}
	}
	return o.Token
}

type GetAuthTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response.
	Object *GetAuthTokenResponseBody
}

func (o *GetAuthTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAuthTokenResponse) GetObject() *GetAuthTokenResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
