// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetEdgeConfigItemRequest struct {
	EdgeConfigID      string `pathParam:"style=simple,explode=false,name=edgeConfigId"`
	EdgeConfigItemKey string `pathParam:"style=simple,explode=false,name=edgeConfigItemKey"`
	// The Team identifier to perform the request on behalf of.
	TeamID *string `queryParam:"style=form,explode=true,name=teamId"`
	// The Team slug to perform the request on behalf of.
	Slug *string `queryParam:"style=form,explode=true,name=slug"`
}

func (o *GetEdgeConfigItemRequest) GetEdgeConfigID() string {
	if o == nil {
		return ""
	}
	return o.EdgeConfigID
}

func (o *GetEdgeConfigItemRequest) GetEdgeConfigItemKey() string {
	if o == nil {
		return ""
	}
	return o.EdgeConfigItemKey
}

func (o *GetEdgeConfigItemRequest) GetTeamID() *string {
	if o == nil {
		return nil
	}
	return o.TeamID
}

func (o *GetEdgeConfigItemRequest) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

type GetEdgeConfigItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The EdgeConfig.
	EdgeConfigItem *components.EdgeConfigItem
}

func (o *GetEdgeConfigItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetEdgeConfigItemResponse) GetEdgeConfigItem() *components.EdgeConfigItem {
	if o == nil {
		return nil
	}
	return o.EdgeConfigItem
}
